ontologies:
  HPO:
    name: Human Phenotype Ontology
    file: ontologies/hp.obo
  DO:
    name: Disease Ontology
    file: ontologies/doid.obo
  MPO:
    name: Mammalian Phenotype Ontology
    file: ontologies/mp.obo
  GO:
    name: Gene Ontology
    file: ontologies/go.obo

default_ontologies:
  - HPO
  - DO

imputation_strategies:
  Age: mean
  Gender: mode
  Height: median
  Phenotype: mode

advanced_imputation_methods:
  - MICE
  - KNN
  - IterativeSVD